### ISSUE TITLE
Running in docker way, I got an error.

### ISSUE THREAD

**Issue by suikascarlet** [Toxblh/skype-to-telegram#23]
After pulled the new image , I can not start it . Could give me some help? THK

```
# docker run --env-file .env toxblh/skype-to-telegram
Wed, 03 Mar 2021 06:17:14 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at node:internal/modules/cjs/loader:1091:14
/code/node_modules/incident/incident.js:129
            throw new TypeError("Missing required `name` argument to `Incident`.");
                  ^

TypeError: Missing required `name` argument to `Incident`.
    at new Incident (/code/node_modules/incident/incident.js:129:19)
    at Object.create (/code/node_modules/skype-http-api/build/lib/errors/http.js:61:16)
    at getLiveKeys (/code/node_modules/skype-http-api/build/lib/providers/microsoft-account.js:99:43)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.login (/code/node_modules/skype-http-api/build/lib/providers/microsoft-account.js:51:26)
    at async Object.login (/code/node_modules/skype-http-api/build/lib/login.js:49:24)
    at async Object.connect (/code/node_modules/skype-http-api/build/lib/connect.js:41:22)
    at async initSkype (/code/dist/index.js:120:11)
```

**Comment by suikaremilia** [comment]
I tried to install it manually again, and it still reported an error. 

`sakuya@suika:~/skype-to-telegram$ yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 5.88s.
sakuya@suika:~/skype-to-telegram$ yarn build
yarn run v1.22.5
$ tsc
Done in 1.87s.
sakuya@suika:~/skype-to-telegram$ node dist/index.js
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal/modules/cjs/loader.js:778:30
(node:12404) UnhandledPromiseRejectionWarning: TypeError: Missing required `name` argument to `Incident`.
    at new Incident (/home/sakuya/skype-to-telegram/node_modules/incident/incident.js:129:19)
    at Object.create (/home/sakuya/skype-to-telegram/node_modules/skype-http-api/build/lib/errors/http.js:61:16)
    at getLiveKeys (/home/sakuya/skype-to-telegram/node_modules/skype-http-api/build/lib/providers/microsoft-account.js:99:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Can you help me? thanks

**Comment by suikaremilia** [comment]
I tried to build it manually again, and it still reported an error.

```
sakuya@suika:~/skype-to-telegram$ yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 5.88s.
sakuya@suika:~/skype-to-telegram$ yarn build
yarn run v1.22.5
$ tsc
Done in 1.87s.
sakuya@suika:~/skype-to-telegram$ node dist/index.js
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal/modules/cjs/loader.js:778:30
(node:12404) UnhandledPromiseRejectionWarning: TypeError: Missing required `name` argument to `Incident`.
    at new Incident (/home/sakuya/skype-to-telegram/node_modules/incident/incident.js:129:19)
    at Object.create (/home/sakuya/skype-to-telegram/node_modules/skype-http-api/build/lib/errors/http.js:61:16)
    at getLiveKeys (/home/sakuya/skype-to-telegram/node_modules/skype-http-api/build/lib/providers/microsoft-account.js:99:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you help me? thanks
